/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/basic/sample-one': RouteRecordInfo<
      '/practices/basic/sample-one',
      '/practices/basic/sample-one',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/basic/sample-two': RouteRecordInfo<
      '/practices/basic/sample-two',
      '/practices/basic/sample-two',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/form-data-binding/form-element-handling-example': RouteRecordInfo<
      '/practices/form-data-binding/form-element-handling-example',
      '/practices/form-data-binding/form-element-handling-example',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/form-data-binding/two-way-data-binding-with-v-model': RouteRecordInfo<
      '/practices/form-data-binding/two-way-data-binding-with-v-model',
      '/practices/form-data-binding/two-way-data-binding-with-v-model',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/form-data-binding/v-model-modifier-example': RouteRecordInfo<
      '/practices/form-data-binding/v-model-modifier-example',
      '/practices/form-data-binding/v-model-modifier-example',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/view-directive/v-bind': RouteRecordInfo<
      '/practices/view-directive/v-bind',
      '/practices/view-directive/v-bind',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/view-directive/v-classbind': RouteRecordInfo<
      '/practices/view-directive/v-classbind',
      '/practices/view-directive/v-classbind',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/view-directive/v-cloak': RouteRecordInfo<
      '/practices/view-directive/v-cloak',
      '/practices/view-directive/v-cloak',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/view-directive/v-for': RouteRecordInfo<
      '/practices/view-directive/v-for',
      '/practices/view-directive/v-for',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/view-directive/v-html': RouteRecordInfo<
      '/practices/view-directive/v-html',
      '/practices/view-directive/v-html',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/view-directive/v-if': RouteRecordInfo<
      '/practices/view-directive/v-if',
      '/practices/view-directive/v-if',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/view-directive/v-memo': RouteRecordInfo<
      '/practices/view-directive/v-memo',
      '/practices/view-directive/v-memo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/view-directive/v-once': RouteRecordInfo<
      '/practices/view-directive/v-once',
      '/practices/view-directive/v-once',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/view-directive/v-pre': RouteRecordInfo<
      '/practices/view-directive/v-pre',
      '/practices/view-directive/v-pre',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/view-directive/v-shorthandbind': RouteRecordInfo<
      '/practices/view-directive/v-shorthandbind',
      '/practices/view-directive/v-shorthandbind',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/view-directive/v-show': RouteRecordInfo<
      '/practices/view-directive/v-show',
      '/practices/view-directive/v-show',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/view-directive/v-stylebind': RouteRecordInfo<
      '/practices/view-directive/v-stylebind',
      '/practices/view-directive/v-stylebind',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/view-directive/v-text': RouteRecordInfo<
      '/practices/view-directive/v-text',
      '/practices/view-directive/v-text',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/vue-event-handling/event-modifier': RouteRecordInfo<
      '/practices/vue-event-handling/event-modifier',
      '/practices/vue-event-handling/event-modifier',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/vue-event-handling/event-object': RouteRecordInfo<
      '/practices/vue-event-handling/event-object',
      '/practices/vue-event-handling/event-object',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/vue-event-handling/v-on': RouteRecordInfo<
      '/practices/vue-event-handling/v-on',
      '/practices/vue-event-handling/v-on',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/practices/vue-style/vue-style-example': RouteRecordInfo<
      '/practices/vue-style/vue-style-example',
      '/practices/vue-style/vue-style-example',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/weather': RouteRecordInfo<
      '/weather',
      '/weather',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/basic/sample-one.vue': {
      routes:
        | '/practices/basic/sample-one'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/basic/sample-two.vue': {
      routes:
        | '/practices/basic/sample-two'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/form-data-binding/form-element-handling-example.vue': {
      routes:
        | '/practices/form-data-binding/form-element-handling-example'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/form-data-binding/two-way-data-binding-with-v-model.vue': {
      routes:
        | '/practices/form-data-binding/two-way-data-binding-with-v-model'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/form-data-binding/v-model-modifier-example.vue': {
      routes:
        | '/practices/form-data-binding/v-model-modifier-example'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/view-directive/v-bind.vue': {
      routes:
        | '/practices/view-directive/v-bind'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/view-directive/v-classbind.vue': {
      routes:
        | '/practices/view-directive/v-classbind'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/view-directive/v-cloak.vue': {
      routes:
        | '/practices/view-directive/v-cloak'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/view-directive/v-for.vue': {
      routes:
        | '/practices/view-directive/v-for'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/view-directive/v-html.vue': {
      routes:
        | '/practices/view-directive/v-html'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/view-directive/v-if.vue': {
      routes:
        | '/practices/view-directive/v-if'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/view-directive/v-memo.vue': {
      routes:
        | '/practices/view-directive/v-memo'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/view-directive/v-once.vue': {
      routes:
        | '/practices/view-directive/v-once'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/view-directive/v-pre.vue': {
      routes:
        | '/practices/view-directive/v-pre'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/view-directive/v-shorthandbind.vue': {
      routes:
        | '/practices/view-directive/v-shorthandbind'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/view-directive/v-show.vue': {
      routes:
        | '/practices/view-directive/v-show'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/view-directive/v-stylebind.vue': {
      routes:
        | '/practices/view-directive/v-stylebind'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/view-directive/v-text.vue': {
      routes:
        | '/practices/view-directive/v-text'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/vue-event-handling/event-modifier.vue': {
      routes:
        | '/practices/vue-event-handling/event-modifier'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/vue-event-handling/event-object.vue': {
      routes:
        | '/practices/vue-event-handling/event-object'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/vue-event-handling/v-on.vue': {
      routes:
        | '/practices/vue-event-handling/v-on'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/practices/vue-style/vue-style-example.vue': {
      routes:
        | '/practices/vue-style/vue-style-example'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/weather.vue': {
      routes:
        | '/weather'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
